
service: my-gcp-simple-function

provider:
  name: google
  runtime: nodejs16
  project: agust-28
  credentials: keyfile.json


plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    handler: hello
    events:
      - http: path
